version: "2"

services:

  app:
    build:
      context: app
      args:
        - MATTERMOST_HUBOT_USERNAME=matterreader
    volumes:
      - /opt/docker/matterreader/volumes/app/home/hubot/matterreader/data:/home/hubot/matterreader/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MATTERMOST_ENDPOINT=/hubot/incoming
      - MATTERMOST_SELFSIGNED_CERT=true
      - MATTERMOST_INCOME_URL=http://xxx.xxx.xxx/hooks/xxxxxxxxxxxxxxxxxxxxx
      - MATTERMOST_TOKEN=xxxxxxxxxxxxxxxxxxxx
    ports:
      - "8001:8080"
